@BookMySlot_HostAddress = http://localhost:5275

GET {{BookMySlot_HostAddress}}/api/users
Accept: application/json

###
POST {{BookMySlot_HostAddress}}/api/users
Content-Type: application/json
{
    "id": 5,
    "name": "Mushahid",
    "email": "mushahidmuzammir@gmail.com",
    "password": "12345",
    "role": "Mesasa"
}

###
GET {{BookMySlot_HostAddress}}/api/sports
Accept: application/json


###
POST {{BookMySlot_HostAddress}}/api/sports
Content-Type: application/json
{
    "name": "Cricket",
    "imageUrl": "images/Pic.jpg"
} 

###
GET {{BookMySlot_HostAddress}}/api/courts
Accept: application/json

###
GET {{BookMySlot_HostAddress}}/api/courts/sport/2
Accept: application/json

###
GET {{BookMySlot_HostAddress}}/api/courts/courtImage/1
Accept: application/json